### ISSUE TITLE
Channel is not responding - with new update

### ISSUE THREAD

**Issue by StinkyDawg** [plexinc-plugins/CBC.bundle#14]
I have just updated to the latest bundle. I get a "Channel is not Responding" message once I get to the level of show listings. So I can find a show, and go to the season, but then when it should list the shows I get the message. 

I can go to the CBC site directly and watch the shows okay. I'm running the latest version of Plex.

Thanks for all your work on this.

**Comment by mikedm139** [comment]
The update relies on an update to the Services.bundle which is bundled with PMS. The service update will become available with the next PMS update.
