### ISSUE TITLE
CBC Bundle : Error loading player: No playable sources found

### ISSUE THREAD

**Issue by danyboy666** [plexinc-plugins/CBC.bundle#22]
PMS Version 0.9.14.4

Even after the PMS update  i'm still having issues playing any CBC content.

"Error loading player: No playable sources found"

**Comment by sander1** [comment]
This sounds like an error with Plex/Web. Can you please try the channel with a different Plex client and see if that works?

**Comment by danyboy666** [comment]
I've tried from 2 different Plex web client both are version 0.9.14.4. SInce there are no other users reporting this i can't be entirely sure it isn't only on my side though.

I have three different plex server setup. My linux install which is still at  0.9.12.19 can't play the updated plugin. But my desktop server install and my NAS install are both at 0.9.14.4 and they definitly have that error.

I activated the logs

 {
    "level": "warn",
    "message": "No type was found for directory",
    "type": "log:message",
    "time": "2015-12-23T22:49:06.976Z"
  },
  {
    "level": "warn",
    "message": "No type was found for directory",
    "type": "log:message",
    "time": "2015-12-23T22:49:06.977Z"
  },
  {
    "level": "warn",
    "message": "No type was found for directory",
    "type": "log:message",
    "time": "2015-12-23T22:49:06.977Z"
  },

...

**Comment by danyboy666** [comment]
Same issue with version 0.9.15.2

**Comment by danyboy666** [comment]
Nevermind the source plays fine in a plex client. As you said the issue lies only with my chrome browser. Source plays fine with edge.

**Comment by danyboy666** [comment]
Well i think this means there won't be a fix for chrome?
