### ISSUE TITLE
add service for watch.cbc.ca

### ISSUE THREAD

**Issue by eetjtl** [plexinc-plugins/CBC.bundle#27]
CBC TV is moving to watch.cbc.ca in the future.
Will need to look at creating a new channel or revamping this one by the end of 2015/2016 season.
It is geoblocked but after that all shows are free.

"You can still watch programs within show websites, just as you do today. CBC.ca/player will continue to feature this content until the end of the 2015/16 season, at which time programs will then be available exclusively at watch.cbc.ca"

**Comment by brddd** [comment]
+1

Some shows (at least Coronation Street) have already moved to watch.cbc.ca.  There are no new episodes through the normal player, but going to watch.cbc.ca there are new episodes.
