### ISSUE TITLE
the TV section is no longer pulling data

### ISSUE THREAD

**Issue by eetjtl** [plexinc-plugins/CBC.bundle#30]
The TV section has moved to watch.cbc.ca
 Maybe someone can pull the needed data for the new code from the rss api.

https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/
(fyi the whole site is geoblocked so need to be in Canada or look like you are in Canada to work on code for this site)

*note the RSS is set to only pull a max of 30 items per page so will need to use 
?offset= , ?offset=30 , ?offset=60  etc to see all of the items  (clearleap:totalResults shows total number of items in sections)
Thanks

**Comment by jnederend** [comment]
Any updates on the switch to the new webplayer?

**Comment by danyboy666** [comment]
`<rss xmlns:media="http://search.yahoo.com/mrss/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:clearleap="http://www.clearleap.com/namespace/clearleap/1.0/" version="2.0">
<channel>
<title>ROOT</title>
<guid>ROOT</guid>
<clearleap:analyticsLabel>ROOT</clearleap:analyticsLabel>
<language>en-us</language>
<ttl>240</ttl>
<link>
https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/
</link>
<pubDate>Mon Oct 24 02:30:59 EDT 2016</pubDate>
<clearleap:totalResults>6</clearleap:totalResults>

<item>
<title>Featured</title>
<guid>e7f0c4cd-2891-4b3d-ac5b-248b7b19a295</guid>
<clearleap:shortcutToGuid>e7f0c4cd-2891-4b3d-ac5b-248b7b19a295</clearleap:shortcutToGuid>
<media:keywords>landing</media:keywords>
<category>Featured</category>
<clearleap:tagline>
<position>Upper Left</position>
<color>#000000</color>
</clearleap:tagline>
<clearleap:analyticsLabel>Featured</clearleap:analyticsLabel>
<clearleap:itemType>LEAF</clearleap:itemType>
<link>
https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/e7f0c4cd-2891-4b3d-ac5b-248b7b19a295
</link>
</item>
<item>
<title>Shows</title>
<guid>2d7279d3-a23d-4a63-a4fa-4091eb2a05fb</guid>
<clearleap:shortcutToGuid>2d7279d3-a23d-4a63-a4fa-4091eb2a05fb</clearleap:shortcutToGuid>
<media:keywords>tabbed</media:keywords>
<category>Shows</category>
<clearleap:tagline>
<position>Upper Left</position>
<color>#000000</color>
</clearleap:tagline>
<clearleap:analyticsLabel>Shows</clearleap:analyticsLabel>
<clearleap:itemType>LEAF</clearleap:itemType>
<link>
https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/2d7279d3-a23d-4a63-a4fa-4091eb2a05fb
</link>
</item>
<item>
<title>Documentaries</title>
<guid>169a521b-1abf-4442-9e06-f471ec5b0465</guid>
<clearleap:shortcutToGuid>169a521b-1abf-4442-9e06-f471ec5b0465</clearleap:shortcutToGuid>
<media:keywords>tabbed</media:keywords>
<category>Documentaries</category>
<clearleap:tagline>
<position>Upper Left</position>
<color>#000000</color>
</clearleap:tagline>
<clearleap:analyticsLabel>Documentaries</clearleap:analyticsLabel>
<clearleap:itemType>LEAF</clearleap:itemType>
<link>
https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/169a521b-1abf-4442-9e06-f471ec5b0465
</link>
</item>
<item>
<title>Kids</title>
<guid>996eae2d-e727-4fa1-9f95-67f9313e9217</guid>
<clearleap:shortcutToGuid>996eae2d-e727-4fa1-9f95-67f9313e9217</clearleap:shortcutToGuid>
<media:keywords>tabbed</media:keywords>
<category>Kids</category>
<clearleap:tagline>
<position>Upper Left</position>
<color>#000000</color>
</clearleap:tagline>
<clearleap:analyticsLabel>Kids</clearleap:analyticsLabel>
<clearleap:itemType>LEAF</clearleap:itemType>
<link>
https://api-cbc.cloud.clearleap.com/cloffice/client/web/browse/996eae2d-e727-4fa1-9f95-67f9313e9217
</link>
</item>
<item>
<title>Identity</title>
<guid>efb34f8f-b6a3-43df-9aa7-6cf5d7cc2b87</guid>
<clearleap:shortcutToGuid>efb34f8f-b6a3-43df-9aa7-6cf5d7cc2b87</clearleap:shortcutToGuid>
<category>Identity</category>
<clearleap:tagline>
<position>Upper Left</position>
<color>#000000</color>
</clearleap:tagline>
<clearleap:analyticsLabel>Identity</clearleap:analyticsLabel>
<clearleap:itemType>IDENTITY</clearleap:itemType>
<link>
https://api-cbc.cloud.clearleap.com/cloffice/client/identities
</link>
</item>
<item>
<title>Search</title>
<guid>fdec0fd7-4358-4c05-bf3f-b4c72c94ea9c</guid>
<clearleap:shortcutToGuid>fdec0fd7-4358-4c05-bf3f-b4c72c94ea9c</clearleap:shortcutToGuid>
<category>Search</category>
<clearleap:tagline>
<position>Upper Left</position>
<color>#000000</color>
</clearleap:tagline>
<clearleap:analyticsLabel>Search</clearleap:analyticsLabel>
<clearleap:itemType>SEARCH</clearleap:itemType>
<link>
https://api-cbc.cloud.clearleap.com/cloffice/client/web/search/
</link>
<clearleap:suggestions>
https://api-cbc.cloud.clearleap.com/cloffice/client/web/suggest/
</clearleap:suggestions>
</item>
</channel>
</rss>`

**Comment by danyboy666** [comment]
[https://gist.github.com/danyboy666/d83fc029892e9436e2fe2e10cbc380f0](url)

**Comment by danyboy666** [comment]
[https://gist.github.com/danyboy666/0b6626cbf17f1a13dcdcf93684838ef7](url)

**Comment by danyboy666** [comment]
[https://gist.github.com/danyboy666/0b6626cbf17f1a13dcdcf93684838ef7](url)
